/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAccordionItem: typeof import('bootstrap-vue-next/components/BAccordion')['BAccordionItem']
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BApp: typeof import('bootstrap-vue-next/components/BApp')['BApp']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('./src/components/commons/bootstrap-vue-next/BButton.vue')['default']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadio']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNav: typeof import('bootstrap-vue-next/components/BNav')['BNav']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    BSearchInput: typeof import('./src/components/commons/bootstrap-vue-next/BSearchInput.vue')['default']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    BToast: typeof import('bootstrap-vue-next/components/BToast')['BToast']
    ClampText: typeof import('./src/components/commons/ClampText.vue')['default']
    DateRangePicker: typeof import('./src/components/commons/DateRangePicker.vue')['default']
    FileIcon: typeof import('./src/components/commons/FileIcon.vue')['default']
    MonthPicker: typeof import('./src/components/commons/MonthPicker.vue')['default']
    RootTree: typeof import('./src/components/commons/tree/RootTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeItem: typeof import('./src/components/commons/tree/TreeItem.vue')['default']
    TreeNode: typeof import('./src/components/commons/tree/TreeNode.vue')['default']
    UIcon: typeof import('./src/components/commons/unplugin-icons/UIcon.vue')['default']
  }
  export interface GlobalDirectives {
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
  }
}
